### ISSUE TITLE
request.response.header is not a function

### ISSUE THREAD

**Issue by NitroGhost** [pankajpatel/hapi-response-time#1]
sometimes I get the following error for seemingly no reason

```
Debug: internal, implementation, error
    TypeError: Uncaught error: request.response.header is not a function
    at \node_modules\hapi-response-time\index.js:13:10
    at each (r\node_modules\hapi\lib\request.js:406:22)
    at iterate (\node_modules\hapi\node_modules\items\lib\index.js:36:13)
    at Object.exports.serial (\node_modules\hapi\node_modules\items\lib\index.js:39:9)
    at _protect.run (\node_modules\hapi\lib\request.js:409:15)
    at internals.Protect.run (\node_modules\hapi\lib\protect.js:62:12)
    at internals.Request._invoke (\node_modules\hapi\lib\request.js:389:19)
    at each (C\node_modules\hapi\lib\request.js:377:25)
    at iterate (\node_modules\hapi\node_modules\items\lib\index.js:36:13)
    at done (\node_modules\hapi\node_modules\items\lib\index.js:28:25)
```

**Comment by NitroGhost** [comment]
this definitely happens without fail when requesting a url that doesn't exist. wouldn't be an issue if it didn't return error 500, when default is 404 for these files

**Comment by pankajpatel** [comment]
Yes, this error appeared to me as well. I am looking into this.

**Comment by pankajpatel** [comment]
https://github.com/hapijs/hapi/issues/1375
